name = "kwanghyun's kb"
description = "ios, macos, swift"
license = "MIT"
homepage = "https://wonkwh.github.io"
min_version = "0.5.0"
demo = "https://zola-after-dark.netlify.com"

[extra]


[author]
name = "Kwanghyun Won"
homepage = "https://wonkwh.github.io"

[original]
author =  "comfusion"
homepage = "https://git.habd.as/comfusion/after-dark/"
repo = "https://git.habd.as/comfusion/after-dark/"
