on:
  push:
    branches:    
      - next         # Push events on next branch
      
          
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: next
      
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        TOKEN: ${{ secrets.TOKEN }}
